# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design\QR.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("design\\../pics/qr-code.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.ui_title = QtWidgets.QLabel(self.centralwidget)
        self.ui_title.setGeometry(QtCore.QRect(210, 40, 381, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ui_title.setFont(font)
        self.ui_title.setMouseTracking(False)
        self.ui_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ui_title.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ui_title.setLineWidth(1)
        self.ui_title.setAlignment(QtCore.Qt.AlignCenter)
        self.ui_title.setObjectName("ui_title")

        self.qr_label = QtWidgets.QLabel(self.centralwidget)
        self.qr_label.setGeometry(QtCore.QRect(320, 125, 161, 161))

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qr_label.sizePolicy().hasHeightForWidth())
        self.qr_label.setSizePolicy(sizePolicy)
        self.qr_label.setMinimumSize(QtCore.QSize(0, 0))
        self.qr_label.setMaximumSize(QtCore.QSize(1000, 1000))
        self.qr_label.setText("")
        self.qr_label.setPixmap(QtGui.QPixmap("design\\../pics/qr-code.png"))
        self.qr_label.setScaledContents(True)
        self.qr_label.setAlignment(QtCore.Qt.AlignCenter)
        self.qr_label.setWordWrap(False)
        self.qr_label.setOpenExternalLinks(False)
        self.qr_label.setObjectName("qr_label")

        self.qrText_label = QtWidgets.QLabel(self.centralwidget)
        self.qrText_label.setGeometry(QtCore.QRect(100, 340, 201, 61))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.qrText_label.setFont(font)
        self.qrText_label.setMouseTracking(False)
        self.qrText_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.qrText_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.qrText_label.setLineWidth(1)
        self.qrText_label.setAlignment(QtCore.Qt.AlignCenter)
        self.qrText_label.setObjectName("qrText_label")

        self.qr_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.qr_textEdit.setGeometry(QtCore.QRect(330, 350, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.qr_textEdit.setFont(font)
        self.qr_textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.qr_textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.qr_textEdit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.qr_textEdit.setCursorWidth(1)
        self.qr_textEdit.setObjectName("qr_textEdit")

        self.submit_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(340, 450, 141, 71))

        # Bind the submit button with its event listener
        self.submit_button.clicked.connect(lambda : self.submitButton_EventListener(MainWindow))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        self.submit_button.setFont(font)
        self.submit_button.setObjectName("submit_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):

        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QR Code Generator"))
        self.ui_title.setText(_translate("MainWindow", "QR Code Generator"))
        self.qrText_label.setText(_translate("MainWindow", "Text to encode"))
        self.submit_button.setText(_translate("MainWindow", "Submit"))

    def submitButton_EventListener(self, MainWindow):
        """Event Listener of the Submit Button."""

        MainWindow.generateQR(self.qr_textEdit)
